version: '3.4'

services:
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=myapp
      - MARIADB_PASSWORD=myapp
      - MARIADB_DATABASE=myapp
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=myapp
      - MARIADB_PASSWORD=myapp
      - MARIADB_DATABASE=myapp
